function [out] = q3(X1,Y1,Z1,U1,V1,W1)
    %Q3 Wrapper for quiver3
    out = quiver3(X1,Y1,Z1,U1,V1,W1,'ShowArrowHead','off','MarkerSize',3,...
        'MarkerEdgeColor',[1 0 0],...
        'Marker','+',...
        'LineWidth',0.2,...
        'LineStyle','--',...
        'AutoScaleFactor',0.0009);
end